export const FLAG_ICONS = [
  { icon: '🇦🇫', label: 'Afghanistan' },
  { icon: '🇦🇱', label: 'Albania' },
  { icon: '🇩🇿', label: 'Algeria' },
  { icon: '🇦🇩', label: 'Andorra' },
  { icon: '🇦🇴', label: 'Angola' },
  { icon: '🇦🇬', label: 'Antigua & Barbuda' },
  { icon: '🇦🇷', label: 'Argentina' },
  { icon: '🇦🇲', label: 'Armenia' },
  { icon: '🇦🇺', label: 'Australia' },
  { icon: '🇦🇹', label: 'Austria' },
  { icon: '🇦🇿', label: 'Azerbaijan' },
  { icon: '🇧🇸', label: 'Bahamas' },
  { icon: '🇧🇭', label: 'Bahrain' },
  { icon: '🇧🇩', label: 'Bangladesh' },
  { icon: '🇧🇧', label: 'Barbados' },
  { icon: '🇧🇾', label: 'Belarus' },
  { icon: '🇧🇪', label: 'Belgium' },
  { icon: '🇧🇿', label: 'Belize' },
  { icon: '🇧🇯', label: 'Benin' },
  { icon: '🇧🇹', label: 'Bhutan' },
  { icon: '🇧🇴', label: 'Bolivia' },
  { icon: '🇧🇦', label: 'Bosnia & Herzegovina' },
  { icon: '🇧🇼', label: 'Botswana' },
  { icon: '🇧🇷', label: 'Brazil' },
  { icon: '🇧🇳', label: 'Brunei' },
  { icon: '🇧🇬', label: 'Bulgaria' },
  { icon: '🇧🇫', label: 'Burkina Faso' },
  { icon: '🇧🇮', label: 'Burundi' },
  { icon: '🇨🇻', label: 'Cabo Verde' },
  { icon: '🇰🇭', label: 'Cambodia' },
  { icon: '🇨🇲', label: 'Cameroon' },
  { icon: '🇨🇦', label: 'Canada' },
  { icon: '🇨🇫', label: 'Central African Republic' },
  { icon: '🇹🇩', label: 'Chad' },
  { icon: '🇨🇱', label: 'Chile' },
  { icon: '🇨🇳', label: 'China' },
  { icon: '🇨🇴', label: 'Colombia' },
  { icon: '🇰🇲', label: 'Comoros' },
  { icon: '🇨🇬', label: 'Congo (Brazzaville)' },
  { icon: '🇨🇩', label: 'Congo (Kinshasa)' },
  { icon: '🇨🇷', label: 'Costa Rica' },
  { icon: '🇨🇮', label: "Côte d'Ivoire" },
  { icon: '🇭🇷', label: 'Croatia' },
  { icon: '🇨🇺', label: 'Cuba' },
  { icon: '🇨🇾', label: 'Cyprus' },
  { icon: '🇨🇿', label: 'Czechia' },
  { icon: '🇩🇰', label: 'Denmark' },
  { icon: '🇩🇯', label: 'Djibouti' },
  { icon: '🇩🇲', label: 'Dominica' },
  { icon: '🇩🇴', label: 'Dominican Republic' },
  { icon: '🇪🇨', label: 'Ecuador' },
  { icon: '🇪🇬', label: 'Egypt' },
  { icon: '🇸🇻', label: 'El Salvador' },
  { icon: '🇬🇶', label: 'Equatorial Guinea' },
  { icon: '🇪🇷', label: 'Eritrea' },
  { icon: '🇪🇪', label: 'Estonia' },
  { icon: '🇸🇿', label: 'Eswatini' },
  { icon: '🇪🇹', label: 'Ethiopia' },
  { icon: '🇫🇯', label: 'Fiji' },
  { icon: '🇫🇮', label: 'Finland' },
  { icon: '🇫🇷', label: 'France' },
  { icon: '🇬🇦', label: 'Gabon' },
  { icon: '🇬🇲', label: 'Gambia' },
  { icon: '🇬🇪', label: 'Georgia' },
  { icon: '🇩🇪', label: 'Germany' },
  { icon: '🇬🇭', label: 'Ghana' },
  { icon: '🇬🇷', label: 'Greece' },
  { icon: '🇬🇩', label: 'Grenada' },
  { icon: '🇬🇹', label: 'Guatemala' },
  { icon: '🇬🇳', label: 'Guinea' },
  { icon: '🇬🇼', label: 'Guinea-Bissau' },
  { icon: '🇬🇾', label: 'Guyana' },
  { icon: '🇭🇹', label: 'Haiti' },
  { icon: '🇭🇳', label: 'Honduras' },
  { icon: '🇭🇺', label: 'Hungary' },
  { icon: '🇮🇸', label: 'Iceland' },
  { icon: '🇮🇳', label: 'India' },
  { icon: '🇮🇩', label: 'Indonesia' },
  { icon: '🇮🇷', label: 'Iran' },
  { icon: '🇮🇶', label: 'Iraq' },
  { icon: '🇮🇪', label: 'Ireland' },
  { icon: '🇮🇱', label: 'Israel' },
  { icon: '🇮🇹', label: 'Italy' },
  { icon: '🇯🇲', label: 'Jamaica' },
  { icon: '🇯🇵', label: 'Japan' },
  { icon: '🇯🇴', label: 'Jordan' },
  { icon: '🇰🇿', label: 'Kazakhstan' },
  { icon: '🇰🇪', label: 'Kenya' },
  { icon: '🇰🇮', label: 'Kiribati' },
  { icon: '🇰🇼', label: 'Kuwait' },
  { icon: '🇰🇬', label: 'Kyrgyzstan' },
  { icon: '🇱🇦', label: 'Laos' },
  { icon: '🇱🇻', label: 'Latvia' },
  { icon: '🇱🇧', label: 'Lebanon' },
  { icon: '🇱🇸', label: 'Lesotho' },
  { icon: '🇱🇷', label: 'Liberia' },
  { icon: '🇱🇾', label: 'Libya' },
  { icon: '🇱🇮', label: 'Liechtenstein' },
  { icon: '🇱🇹', label: 'Lithuania' },
  { icon: '🇱🇺', label: 'Luxembourg' },
  { icon: '🇲🇬', label: 'Madagascar' },
  { icon: '🇲🇼', label: 'Malawi' },
  { icon: '🇲🇾', label: 'Malaysia' },
  { icon: '🇲🇻', label: 'Maldives' },
  { icon: '🇲🇱', label: 'Mali' },
  { icon: '🇲🇹', label: 'Malta' },
  { icon: '🇲🇭', label: 'Marshall Islands' },
  { icon: '🇲🇷', label: 'Mauritania' },
  { icon: '🇲🇺', label: 'Mauritius' },
  { icon: '🇲🇽', label: 'Mexico' },
  { icon: '🇫🇲', label: 'Micronesia' },
  { icon: '🇲🇩', label: 'Moldova' },
  { icon: '🇲🇨', label: 'Monaco' },
  { icon: '🇲🇳', label: 'Mongolia' },
  { icon: '🇲🇪', label: 'Montenegro' },
  { icon: '🇲🇦', label: 'Morocco' },
  { icon: '🇲🇿', label: 'Mozambique' },
  { icon: '🇲🇲', label: 'Myanmar' },
  { icon: '🇳🇦', label: 'Namibia' },
  { icon: '🇳🇷', label: 'Nauru' },
  { icon: '🇳🇵', label: 'Nepal' },
  { icon: '🇳🇱', label: 'Netherlands' },
  { icon: '🇳🇿', label: 'New Zealand' },
  { icon: '🇳🇮', label: 'Nicaragua' },
  { icon: '🇳🇪', label: 'Niger' },
  { icon: '🇳🇬', label: 'Nigeria' },
  { icon: '🇰🇵', label: 'North Korea' },
  { icon: '🇲🇰', label: 'North Macedonia' },
  { icon: '🇳🇴', label: 'Norway' },
  { icon: '🇴🇲', label: 'Oman' },
  { icon: '🇵🇰', label: 'Pakistan' },
  { icon: '🇵🇼', label: 'Palau' },
  { icon: '🇵🇸', label: 'Palestine' },
  { icon: '🇵🇦', label: 'Panama' },
  { icon: '🇵🇬', label: 'Papua New Guinea' },
  { icon: '🇵🇾', label: 'Paraguay' },
  { icon: '🇵🇪', label: 'Peru' },
  { icon: '🇵🇭', label: 'Philippines' },
  { icon: '🇵🇱', label: 'Poland' },
  { icon: '🇵🇹', label: 'Portugal' },
  { icon: '🇶🇦', label: 'Qatar' },
  { icon: '🇷🇴', label: 'Romania' },
  { icon: '🇷🇺', label: 'Russia' },
  { icon: '🇷🇼', label: 'Rwanda' },
  { icon: '🇰🇳', label: 'St. Kitts & Nevis' },
  { icon: '🇱🇨', label: 'St. Lucia' },
  { icon: '🇻🇨', label: 'St. Vincent & Grenadines' },
  { icon: '🇼🇸', label: 'Samoa' },
  { icon: '🇸🇲', label: 'San Marino' },
  { icon: '🇸🇹', label: 'São Tomé & Príncipe' },
  { icon: '🇸🇦', label: 'Saudi Arabia' },
  { icon: '🇸🇳', label: 'Senegal' },
  { icon: '🇷🇸', label: 'Serbia' },
  { icon: '🇸🇨', label: 'Seychelles' },
  { icon: '🇸🇱', label: 'Sierra Leone' },
  { icon: '🇸🇬', label: 'Singapore' },
  { icon: '🇸🇰', label: 'Slovakia' },
  { icon: '🇸🇮', label: 'Slovenia' },
  { icon: '🇸🇧', label: 'Solomon Islands' },
  { icon: '🇸🇴', label: 'Somalia' },
  { icon: '🇿🇦', label: 'South Africa' },
  { icon: '🇰🇷', label: 'South Korea' },
  { icon: '🇸🇸', label: 'South Sudan' },
  { icon: '🇪🇸', label: 'Spain' },
  { icon: '🇱🇰', label: 'Sri Lanka' },
  { icon: '🇸🇩', label: 'Sudan' },
  { icon: '🇸🇷', label: 'Suriname' },
  { icon: '🇸🇪', label: 'Sweden' },
  { icon: '🇨🇭', label: 'Switzerland' },
  { icon: '🇸🇾', label: 'Syria' },
  { icon: '🇹🇼', label: 'Taiwan' },
  { icon: '🇹🇯', label: 'Tajikistan' },
  { icon: '🇹🇿', label: 'Tanzania' },
  { icon: '🇹🇭', label: 'Thailand' },
  { icon: '🇹🇱', label: 'Timor-Leste' },
  { icon: '🇹🇬', label: 'Togo' },
  { icon: '🇹🇴', label: 'Tonga' },
  { icon: '🇹🇹', label: 'Trinidad & Tobago' },
  { icon: '🇹🇳', label: 'Tunisia' },
  { icon: '🇹🇷', label: 'Turkey' },
  { icon: '🇹🇲', label: 'Turkmenistan' },
  { icon: '🇹🇻', label: 'Tuvalu' },
  { icon: '🇺🇬', label: 'Uganda' },
  { icon: '🇺🇦', label: 'Ukraine' },
  { icon: '🇦🇪', label: 'United Arab Emirates' },
  { icon: '🇬🇧', label: 'United Kingdom' },
  { icon: '🇺🇸', label: 'United States' },
  { icon: '🇺🇾', label: 'Uruguay' },
  { icon: '🇺🇿', label: 'Uzbekistan' },
  { icon: '🇻🇺', label: 'Vanuatu' },
  { icon: '🇻🇦', label: 'Vatican City' },
  { icon: '🇻🇪', label: 'Venezuela' },
  { icon: '🇻🇳', label: 'Vietnam' },
  { icon: '🇾🇪', label: 'Yemen' },
  { icon: '🇿🇲', label: 'Zambia' },
  { icon: '🇿🇼', label: 'Zimbabwe' },
  { icon: '🇭🇰', label: 'Hong Kong' },
  { icon: '🇲🇴', label: 'Macau' },
  { icon: '🇽🇰', label: 'Kosovo' },
  { icon: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', label: 'England' },
  { icon: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', label: 'Scotland' },
  { icon: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', label: 'Wales' },
  { icon: '🇪🇺', label: 'European Union' },
  { icon: '🇺🇳', label: 'United Nations' },
];

export const CATEGORY_ICONS = [
  { icon: '📰', label: 'News' },
  { icon: '🗞️', label: 'Newspaper' },
  { icon: '💻', label: 'Technology' },
  { icon: '🖥️', label: 'Computer' },
  { icon: '⌨️', label: 'Keyboard' },
  { icon: '🔧', label: 'Tools' },
  { icon: '⚙️', label: 'Settings' },
  { icon: '🌍', label: 'World' },
  { icon: '📚', label: 'Education' },
  { icon: '🎮', label: 'Gaming' },
  { icon: '🎬', label: 'Movies' },
  { icon: '🛒', label: 'Shopping' },
  { icon: '🏦', label: 'Finance' },
  { icon: '⚕️', label: 'Health' },
  { icon: '🎵', label: 'Music' },
  { icon: '✈️', label: 'Travel' },
  { icon: '🍳', label: 'Food' },
  { icon: '⚽', label: 'Sports' },
  { icon: '🏠', label: 'Home' },
  { icon: '📧', label: 'Email' },
  { icon: '💬', label: 'Social' },
  { icon: '📹', label: 'Video' },
  { icon: '📸', label: 'Photos' },
  { icon: '🎨', label: 'Art' },
  { icon: '📖', label: 'Books' },
  { icon: '🔬', label: 'Science' },
  { icon: '🚀', label: 'Space' },
  { icon: '🤖', label: 'AI' },
  { icon: '📱', label: 'Mobile' },
  { icon: '🛡️', label: 'Security' },
  { icon: '💰', label: 'Crypto' },
  { icon: '🔒', label: 'Privacy' },
  { icon: '💊', label: 'Medicine' },
  { icon: '🌱', label: 'Environment' },
  { icon: '📡', label: 'Telecom' },
  { icon: '🎧', label: 'Podcasts' },
  { icon: '☁️', label: 'Cloud' },
  { icon: '📊', label: 'Analytics' },
  { icon: '🎯', label: 'Productivity' },
  { icon: '🔗', label: 'Links' },
  { icon: '🧬', label: 'Biotech' },
  { icon: '🏗️', label: 'Startups' },
  { icon: '📦', label: 'E-commerce' },
  { icon: '🎙️', label: 'Radio' },
  { icon: '💡', label: 'Ideas' },
  { icon: '🛰️', label: 'Satellite' },
  { icon: '🤝', label: 'Business' },
  { icon: '🚗', label: 'Automotive' },
  { icon: '🏷️', label: 'Deals' },
];
