export const FLAG_ICONS = [
  { icon: '🇦🇫', label: 'Afghanistan' },
  { icon: '🇦🇱', label: 'Albania' },
  { icon: '🇩🇿', label: 'Algeria' },
  { icon: '🇦🇩', label: 'Andorra' },
  { icon: '🇦🇴', label: 'Angola' },
  { icon: '🇦🇬', label: 'Antigua & Barbuda' },
  { icon: '🇦🇷', label: 'Argentina' },
  { icon: '🇦🇲', label: 'Armenia' },
  { icon: '🇦🇺', label: 'Australia' },
  { icon: '🇦🇹', label: 'Austria' },
  { icon: '🇦🇿', label: 'Azerbaijan' },
  { icon: '🇧🇸', label: 'Bahamas' },
  { icon: '🇧🇭', label: 'Bahrain' },
  { icon: '🇧🇩', label: 'Bangladesh' },
  { icon: '🇧🇧', label: 'Barbados' },
  { icon: '🇧🇾', label: 'Belarus' },
  { icon: '🇧🇪', label: 'Belgium' },
  { icon: '🇧🇿', label: 'Belize' },
  { icon: '🇧🇯', label: 'Benin' },
  { icon: '🇧🇹', label: 'Bhutan' },
  { icon: '🇧🇴', label: 'Bolivia' },
  { icon: '🇧🇦', label: 'Bosnia & Herzegovina' },
  { icon: '🇧🇼', label: 'Botswana' },
  { icon: '🇧🇷', label: 'Brazil' },
  { icon: '🇧🇳', label: 'Brunei' },
  { icon: '🇧🇬', label: 'Bulgaria' },
  { icon: '🇧🇫', label: 'Burkina Faso' },
  { icon: '🇧🇮', label: 'Burundi' },
  { icon: '🇨🇻', label: 'Cabo Verde' },
  { icon: '🇰🇭', label: 'Cambodia' },
  { icon: '🇨🇲', label: 'Cameroon' },
  { icon: '🇨🇦', label: 'Canada' },
  { icon: '🇨🇫', label: 'Central African Republic' },
  { icon: '🇹🇩', label: 'Chad' },
  { icon: '🇨🇱', label: 'Chile' },
  { icon: '🇨🇳', label: 'China' },
  { icon: '🇨🇴', label: 'Colombia' },
  { icon: '🇰🇲', label: 'Comoros' },
  { icon: '🇨🇬', label: 'Congo (Brazzaville)' },
  { icon: '🇨🇩', label: 'Congo (Kinshasa)' },
  { icon: '🇨🇷', label: 'Costa Rica' },
  { icon: '🇨🇮', label: "Côte d'Ivoire" },
  { icon: '🇭🇷', label: 'Croatia' },
  { icon: '🇨🇺', label: 'Cuba' },
  { icon: '🇨🇾', label: 'Cyprus' },
  { icon: '🇨🇿', label: 'Czechia' },
  { icon: '🇩🇰', label: 'Denmark' },
  { icon: '🇩🇯', label: 'Djibouti' },
  { icon: '🇩🇲', label: 'Dominica' },
  { icon: '🇩🇴', label: 'Dominican Republic' },
  { icon: '🇪🇨', label: 'Ecuador' },
  { icon: '🇪🇬', label: 'Egypt' },
  { icon: '🇸🇻', label: 'El Salvador' },
  { icon: '🇬🇶', label: 'Equatorial Guinea' },
  { icon: '🇪🇷', label: 'Eritrea' },
  { icon: '🇪🇪', label: 'Estonia' },
  { icon: '🇸🇿', label: 'Eswatini' },
  { icon: '🇪🇹', label: 'Ethiopia' },
  { icon: '🇫🇯', label: 'Fiji' },
  { icon: '🇫🇮', label: 'Finland' },
  { icon: '🇫🇷', label: 'France' },
  { icon: '🇬🇦', label: 'Gabon' },
  { icon: '🇬🇲', label: 'Gambia' },
  { icon: '🇬🇪', label: 'Georgia' },
  { icon: '🇩🇪', label: 'Germany' },
  { icon: '🇬🇭', label: 'Ghana' },
  { icon: '🇬🇷', label: 'Greece' },
  { icon: '🇬🇩', label: 'Grenada' },
  { icon: '🇬🇹', label: 'Guatemala' },
  { icon: '🇬🇳', label: 'Guinea' },
  { icon: '🇬🇼', label: 'Guinea-Bissau' },
  { icon: '🇬🇾', label: 'Guyana' },
  { icon: '🇭🇹', label: 'Haiti' },
  { icon: '🇭🇳', label: 'Honduras' },
  { icon: '🇭🇺', label: 'Hungary' },
  { icon: '🇮🇸', label: 'Iceland' },
  { icon: '🇮🇳', label: 'India' },
  { icon: '🇮🇩', label: 'Indonesia' },
  { icon: '🇮🇷', label: 'Iran' },
  { icon: '🇮🇶', label: 'Iraq' },
  { icon: '🇮🇪', label: 'Ireland' },
  { icon: '🇮🇱', label: 'Israel' },
  { icon: '🇮🇹', label: 'Italy' },
  { icon: '🇯🇲', label: 'Jamaica' },
  { icon: '🇯🇵', label: 'Japan' },
  { icon: '🇯🇴', label: 'Jordan' },
  { icon: '🇰🇿', label: 'Kazakhstan' },
  { icon: '🇰🇪', label: 'Kenya' },
  { icon: '🇰🇮', label: 'Kiribati' },
  { icon: '🇰🇼', label: 'Kuwait' },
  { icon: '🇰🇬', label: 'Kyrgyzstan' },
  { icon: '🇱🇦', label: 'Laos' },
  { icon: '🇱🇻', label: 'Latvia' },
  { icon: '🇱🇧', label: 'Lebanon' },
  { icon: '🇱🇸', label: 'Lesotho' },
  { icon: '🇱🇷', label: 'Liberia' },
  { icon: '🇱🇾', label: 'Libya' },
  { icon: '🇱🇮', label: 'Liechtenstein' },
  { icon: '🇱🇹', label: 'Lithuania' },
  { icon: '🇱🇺', label: 'Luxembourg' },
  { icon: '🇲🇬', label: 'Madagascar' },
  { icon: '🇲🇼', label: 'Malawi' },
  { icon: '🇲🇾', label: 'Malaysia' },
  { icon: '🇲🇻', label: 'Maldives' },
  { icon: '🇲🇱', label: 'Mali' },
  { icon: '🇲🇹', label: 'Malta' },
  { icon: '🇲🇭', label: 'Marshall Islands' },
  { icon: '🇲🇷', label: 'Mauritania' },
  { icon: '🇲🇺', label: 'Mauritius' },
  { icon: '🇲🇽', label: 'Mexico' },
  { icon: '🇫🇲', label: 'Micronesia' },
  { icon: '🇲🇩', label: 'Moldova' },
  { icon: '🇲🇨', label: 'Monaco' },
  { icon: '🇲🇳', label: 'Mongolia' },
  { icon: '🇲🇪', label: 'Montenegro' },
  { icon: '🇲🇦', label: 'Morocco' },
  { icon: '🇲🇿', label: 'Mozambique' },
  { icon: '🇲🇲', label: 'Myanmar' },
  { icon: '🇳🇦', label: 'Namibia' },
  { icon: '🇳🇷', label: 'Nauru' },
  { icon: '🇳🇵', label: 'Nepal' },
  { icon: '🇳🇱', label: 'Netherlands' },
  { icon: '🇳🇿', label: 'New Zealand' },
  { icon: '🇳🇮', label: 'Nicaragua' },
  { icon: '🇳🇪', label: 'Niger' },
  { icon: '🇳🇬', label: 'Nigeria' },
  { icon: '🇰🇵', label: 'North Korea' },
  { icon: '🇲🇰', label: 'North Macedonia' },
  { icon: '🇳🇴', label: 'Norway' },
  { icon: '🇴🇲', label: 'Oman' },
  { icon: '🇵🇰', label: 'Pakistan' },
  { icon: '🇵🇼', label: 'Palau' },
  { icon: '🇵🇸', label: 'Palestine' },
  { icon: '🇵🇦', label: 'Panama' },
  { icon: '🇵🇬', label: 'Papua New Guinea' },
  { icon: '🇵🇾', label: 'Paraguay' },
  { icon: '🇵🇪', label: 'Peru' },
  { icon: '🇵🇭', label: 'Philippines' },
  { icon: '🇵🇱', label: 'Poland' },
  { icon: '🇵🇹', label: 'Portugal' },
  { icon: '🇶🇦', label: 'Qatar' },
  { icon: '🇷🇴', label: 'Romania' },
  { icon: '🇷🇺', label: 'Russia' },
  { icon: '🇷🇼', label: 'Rwanda' },
  { icon: '🇰🇳', label: 'St. Kitts & Nevis' },
  { icon: '🇱🇨', label: 'St. Lucia' },
  { icon: '🇻🇨', label: 'St. Vincent & Grenadines' },
  { icon: '🇼🇸', label: 'Samoa' },
  { icon: '🇸🇲', label: 'San Marino' },
  { icon: '🇸🇹', label: 'São Tomé & Príncipe' },
  { icon: '🇸🇦', label: 'Saudi Arabia' },
  { icon: '🇸🇳', label: 'Senegal' },
  { icon: '🇷🇸', label: 'Serbia' },
  { icon: '🇸🇨', label: 'Seychelles' },
  { icon: '🇸🇱', label: 'Sierra Leone' },
  { icon: '🇸🇬', label: 'Singapore' },
  { icon: '🇸🇰', label: 'Slovakia' },
  { icon: '🇸🇮', label: 'Slovenia' },
  { icon: '🇸🇧', label: 'Solomon Islands' },
  { icon: '🇸🇴', label: 'Somalia' },
  { icon: '🇿🇦', label: 'South Africa' },
  { icon: '🇰🇷', label: 'South Korea' },
  { icon: '🇸🇸', label: 'South Sudan' },
  { icon: '🇪🇸', label: 'Spain' },
  { icon: '🇱🇰', label: 'Sri Lanka' },
  { icon: '🇸🇩', label: 'Sudan' },
  { icon: '🇸🇷', label: 'Suriname' },
  { icon: '🇸🇪', label: 'Sweden' },
  { icon: '🇨🇭', label: 'Switzerland' },
  { icon: '🇸🇾', label: 'Syria' },
  { icon: '🇹🇼', label: 'Taiwan' },
  { icon: '🇹🇯', label: 'Tajikistan' },
  { icon: '🇹🇿', label: 'Tanzania' },
  { icon: '🇹🇭', label: 'Thailand' },
  { icon: '🇹🇱', label: 'Timor-Leste' },
  { icon: '🇹🇬', label: 'Togo' },
  { icon: '🇹🇴', label: 'Tonga' },
  { icon: '🇹🇹', label: 'Trinidad & Tobago' },
  { icon: '🇹🇳', label: 'Tunisia' },
  { icon: '🇹🇷', label: 'Turkey' },
  { icon: '🇹🇲', label: 'Turkmenistan' },
  { icon: '🇹🇻', label: 'Tuvalu' },
  { icon: '🇺🇬', label: 'Uganda' },
  { icon: '🇺🇦', label: 'Ukraine' },
  { icon: '🇦🇪', label: 'United Arab Emirates' },
  { icon: '🇬🇧', label: 'United Kingdom' },
  { icon: '🇺🇸', label: 'United States' },
  { icon: '🇺🇾', label: 'Uruguay' },
  { icon: '🇺🇿', label: 'Uzbekistan' },
  { icon: '🇻🇺', label: 'Vanuatu' },
  { icon: '🇻🇦', label: 'Vatican City' },
  { icon: '🇻🇪', label: 'Venezuela' },
  { icon: '🇻🇳', label: 'Vietnam' },
  { icon: '🇾🇪', label: 'Yemen' },
  { icon: '🇿🇲', label: 'Zambia' },
  { icon: '🇿🇼', label: 'Zimbabwe' },
  { icon: '🇭🇰', label: 'Hong Kong' },
  { icon: '🇲🇴', label: 'Macau' },
  { icon: '🇽🇰', label: 'Kosovo' },
  { icon: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', label: 'England' },
  { icon: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', label: 'Scotland' },
  { icon: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', label: 'Wales' },
  { icon: '🇪🇺', label: 'European Union' },
  { icon: '🇺🇳', label: 'United Nations' },
];

export const CATEGORY_ICONS = [
  { icon: '📰', label: 'News' },
  { icon: '🗞️', label: 'Newspaper' },
  { icon: '📻', label: 'Radio' },
  { icon: '📺', label: 'TV' },
  { icon: '🎙️', label: 'Podcast' },
  { icon: '💻', label: 'Technology' },
  { icon: '🖥️', label: 'Computer' },
  { icon: '⌨️', label: 'Keyboard' },
  { icon: '🖱️', label: 'Mouse' },
  { icon: '🖨️', label: 'Printer' },
  { icon: '📱', label: 'Mobile' },
  { icon: '📲', label: 'Apps' },
  { icon: '💾', label: 'Storage' },
  { icon: '💿', label: 'CD' },
  { icon: '📀', label: 'DVD' },
  { icon: '🕹️', label: 'Joystick' },
  { icon: '🎮', label: 'Gaming' },
  { icon: '👾', label: 'Retro Gaming' },
  { icon: '🎲', label: 'Board Games' },
  { icon: '♟️', label: 'Chess' },
  { icon: '🎯', label: 'Darts' },
  { icon: '🎳', label: 'Bowling' },
  { icon: '🎰', label: 'Casino' },
  { icon: '🔧', label: 'Tools' },
  { icon: '🔨', label: 'Hammer' },
  { icon: '🪛', label: 'Screwdriver' },
  { icon: '🔩', label: 'Hardware' },
  { icon: '⚙️', label: 'Settings' },
  { icon: '🛠️', label: 'Repair' },
  { icon: '🌍', label: 'World' },
  { icon: '🌎', label: 'Americas' },
  { icon: '🌏', label: 'Asia' },
  { icon: '🌐', label: 'Internet' },
  { icon: '🗺️', label: 'Map' },
  { icon: '🧭', label: 'Compass' },
  { icon: '🏔️', label: 'Mountains' },
  { icon: '🏕️', label: 'Camping' },
  { icon: '🏖️', label: 'Beach' },
  { icon: '🏝️', label: 'Island' },
  { icon: '🏜️', label: 'Desert' },
  { icon: '📚', label: 'Education' },
  { icon: '📖', label: 'Books' },
  { icon: '📕', label: 'Textbook' },
  { icon: '📓', label: 'Notebook' },
  { icon: '📝', label: 'Writing' },
  { icon: '✏️', label: 'Pencil' },
  { icon: '🖊️', label: 'Pen' },
  { icon: '🎓', label: 'Graduation' },
  { icon: '🏫', label: 'School' },
  { icon: '🧪', label: 'Experiment' },
  { icon: '🔬', label: 'Science' },
  { icon: '🔭', label: 'Telescope' },
  { icon: '🧬', label: 'Biotech' },
  { icon: '🧮', label: 'Math' },
  { icon: '🎬', label: 'Movies' },
  { icon: '🎥', label: 'Cinema' },
  { icon: '🎞️', label: 'Film' },
  { icon: '🍿', label: 'Popcorn' },
  { icon: '🎭', label: 'Theater' },
  { icon: '🎪', label: 'Circus' },
  { icon: '🤹', label: 'Juggling' },
  { icon: '🛒', label: 'Shopping' },
  { icon: '🛍️', label: 'Shopping Bags' },
  { icon: '🧾', label: 'Receipt' },
  { icon: '🏷️', label: 'Deals' },
  { icon: '💳', label: 'Credit Card' },
  { icon: '🏦', label: 'Finance' },
  { icon: '💰', label: 'Crypto' },
  { icon: '💵', label: 'Cash' },
  { icon: '💸', label: 'Money' },
  { icon: '📈', label: 'Stocks' },
  { icon: '📉', label: 'Markets' },
  { icon: '📊', label: 'Analytics' },
  { icon: '🏛️', label: 'Government' },
  { icon: '⚖️', label: 'Law' },
  { icon: '🗳️', label: 'Politics' },
  { icon: '📜', label: 'History' },
  { icon: '⚕️', label: 'Health' },
  { icon: '💊', label: 'Medicine' },
  { icon: '🩺', label: 'Doctor' },
  { icon: '🩹', label: 'Bandage' },
  { icon: '💉', label: 'Vaccine' },
  { icon: '🧘', label: 'Yoga' },
  { icon: '🧠', label: 'Psychology' },
  { icon: '🫀', label: 'Heart' },
  { icon: '🦷', label: 'Dental' },
  { icon: '👁️', label: 'Vision' },
  { icon: '🎵', label: 'Music' },
  { icon: '🎶', label: 'Notes' },
  { icon: '🎸', label: 'Guitar' },
  { icon: '🎹', label: 'Piano' },
  { icon: '🥁', label: 'Drums' },
  { icon: '🎺', label: 'Trumpet' },
  { icon: '🎻', label: 'Violin' },
  { icon: '🎤', label: 'Singer' },
  { icon: '🎧', label: 'Headphones' },
  { icon: '🎼', label: 'Sheet Music' },
  { icon: '✈️', label: 'Travel' },
  { icon: '🛫', label: 'Flight' },
  { icon: '🚢', label: 'Cruise' },
  { icon: '🚆', label: 'Train' },
  { icon: '🚌', label: 'Bus' },
  { icon: '🏨', label: 'Hotel' },
  { icon: '🧳', label: 'Luggage' },
  { icon: '🏰', label: 'Castle' },
  { icon: '🗽', label: 'Landmark' },
  { icon: '🎡', label: 'Amusement Park' },
  { icon: '🍳', label: 'Food' },
  { icon: '🍔', label: 'Burger' },
  { icon: '🍕', label: 'Pizza' },
  { icon: '🍣', label: 'Sushi' },
  { icon: '🥗', label: 'Salad' },
  { icon: '🍰', label: 'Cake' },
  { icon: '☕', label: 'Coffee' },
  { icon: '🍺', label: 'Beer' },
  { icon: '🍷', label: 'Wine' },
  { icon: '🧁', label: 'Dessert' },
  { icon: '🍩', label: 'Donut' },
  { icon: '🌮', label: 'Taco' },
  { icon: '🥩', label: 'Steak' },
  { icon: '⚽', label: 'Soccer' },
  { icon: '🏀', label: 'Basketball' },
  { icon: '🏈', label: 'Football' },
  { icon: '⚾', label: 'Baseball' },
  { icon: '🎾', label: 'Tennis' },
  { icon: '🏐', label: 'Volleyball' },
  { icon: '🏉', label: 'Rugby' },
  { icon: '🥎', label: 'Softball' },
  { icon: '🏏', label: 'Cricket' },
  { icon: '🏑', label: 'Field Hockey' },
  { icon: '🏒', label: 'Ice Hockey' },
  { icon: '🏓', label: 'Ping Pong' },
  { icon: '🏸', label: 'Badminton' },
  { icon: '🥊', label: 'Boxing' },
  { icon: '🥋', label: 'Martial Arts' },
  { icon: '🥅', label: 'Goal' },
  { icon: '⛳', label: 'Golf' },
  { icon: '⛸️', label: 'Ice Skating' },
  { icon: '🎿', label: 'Skiing' },
  { icon: '🛹', label: 'Skateboarding' },
  { icon: '🏂', label: 'Snowboarding' },
  { icon: '🏊', label: 'Swimming' },
  { icon: '🤿', label: 'Diving' },
  { icon: '🚴', label: 'Cycling' },
  { icon: '🧗', label: 'Climbing' },
  { icon: '🤸', label: 'Gymnastics' },
  { icon: '🏋️', label: 'Weightlifting' },
  { icon: '🏌️', label: 'Golfing' },
  { icon: '🏇', label: 'Horse Racing' },
  { icon: '🎣', label: 'Fishing' },
  { icon: '🏠', label: 'Home' },
  { icon: '🏡', label: 'House' },
  { icon: '🛋️', label: 'Furniture' },
  { icon: '🪴', label: 'Plants' },
  { icon: '🌻', label: 'Flowers' },
  { icon: '🌳', label: 'Nature' },
  { icon: '🐶', label: 'Dogs' },
  { icon: '🐱', label: 'Cats' },
  { icon: '🐾', label: 'Pets' },
  { icon: '👶', label: 'Babies' },
  { icon: '🧒', label: 'Kids' },
  { icon: '👨‍👩‍👧‍👦', label: 'Family' },
  { icon: '💍', label: 'Wedding' },
  { icon: '🎂', label: 'Birthday' },
  { icon: '🎁', label: 'Gifts' },
  { icon: '🎄', label: 'Christmas' },
  { icon: '🎃', label: 'Halloween' },
  { icon: '🐰', label: 'Easter' },
  { icon: '🕎', label: 'Hanukkah' },
  { icon: '📧', label: 'Email' },
  { icon: '📬', label: 'Mail' },
  { icon: '💬', label: 'Social' },
  { icon: '💭', label: 'Thought' },
  { icon: '🗨️', label: 'Chat' },
  { icon: '📣', label: 'Announcement' },
  { icon: '📢', label: 'Loudspeaker' },
  { icon: '🔔', label: 'Notifications' },
  { icon: '📹', label: 'Video' },
  { icon: '🎦', label: 'Cinema Screen' },
  { icon: '▶️', label: 'Play' },
  { icon: '⏯️', label: 'Media' },
  { icon: '📸', label: 'Photos' },
  { icon: '📷', label: 'Camera' },
  { icon: '🖼️', label: 'Gallery' },
  { icon: '🎨', label: 'Art' },
  { icon: '🖌️', label: 'Painting' },
  { icon: '🖍️', label: 'Crayon' },
  { icon: '🧵', label: 'Sewing' },
  { icon: '🧶', label: 'Knitting' },
  { icon: '🚀', label: 'Space' },
  { icon: '🛸', label: 'UFO' },
  { icon: '🌙', label: 'Moon' },
  { icon: '⭐', label: 'Star' },
  { icon: '☀️', label: 'Sun' },
  { icon: '☁️', label: 'Cloud' },
  { icon: '🌧️', label: 'Rain' },
  { icon: '⛈️', label: 'Storm' },
  { icon: '🌈', label: 'Rainbow' },
  { icon: '🔥', label: 'Fire' },
  { icon: '💧', label: 'Water' },
  { icon: '🌊', label: 'Ocean' },
  { icon: '🤖', label: 'AI' },
  { icon: '💡', label: 'Ideas' },
  { icon: '🔑', label: 'Password' },
  { icon: '🛡️', label: 'Security' },
  { icon: '🔒', label: 'Privacy' },
  { icon: '🔐', label: 'Locked' },
  { icon: '📡', label: 'Telecom' },
  { icon: '🛰️', label: 'Satellite' },
  { icon: '📶', label: 'Signal' },
  { icon: '🖧', label: 'Network' },
  { icon: '🔗', label: 'Links' },
  { icon: '🌱', label: 'Environment' },
  { icon: '♻️', label: 'Recycling' },
  { icon: '⚡', label: 'Energy' },
  { icon: '☢️', label: 'Nuclear' },
  { icon: '🧲', label: 'Magnetism' },
  { icon: '🏗️', label: 'Startups' },
  { icon: '🏢', label: 'Corporate' },
  { icon: '🏭', label: 'Industry' },
  { icon: '📦', label: 'E-commerce' },
  { icon: '🚚', label: 'Delivery' },
  { icon: '🏪', label: 'Store' },
  { icon: '🤝', label: 'Business' },
  { icon: '📋', label: 'Tasks' },
  { icon: '📅', label: 'Calendar' },
  { icon: '⏰', label: 'Alarm' },
  { icon: '🕐', label: 'Time' },
  { icon: '🚗', label: 'Automotive' },
  { icon: '🚙', label: 'SUV' },
  { icon: '🏎️', label: 'Racing' },
  { icon: '🚲', label: 'Bicycle' },
  { icon: '🛵', label: 'Scooter' },
  { icon: '🏍️', label: 'Motorcycle' },
  { icon: '⛽', label: 'Fuel' },
  { icon: '🔋', label: 'Battery' },
  { icon: '⌚', label: 'Watch' },
  { icon: '🧹', label: 'Cleaning' },
  { icon: '🧯', label: 'Fire Extinguisher' },
  { icon: '🚑', label: 'Ambulance' },
  { icon: '🚒', label: 'Fire Truck' },
  { icon: '🚓', label: 'Police' },
  { icon: '👮', label: 'Law Enforcement' },
  { icon: '🦸', label: 'Hero' },
  { icon: '🦹', label: 'Villain' },
  { icon: '👻', label: 'Ghost' },
  { icon: '👽', label: 'Alien' },
  { icon: '🧛', label: 'Vampire' },
  { icon: '🧙', label: 'Magic' },
  { icon: '🧚', label: 'Fairy' },
  { icon: '🧜', label: 'Mermaid' },
  { icon: '🗿', label: 'Ancient' },
  { icon: '⛩️', label: 'Shrine' },
  { icon: '🕌', label: 'Mosque' },
  { icon: '⛪', label: 'Church' },
  { icon: '🕍', label: 'Synagogue' },
  { icon: '🛕', label: 'Temple' },
  { icon: '🧧', label: 'Lunar New Year' },
  { icon: '🎊', label: 'Celebration' },
  { icon: '🥳', label: 'Party' },
  { icon: '🎉', label: 'Confetti' },
  { icon: '💐', label: 'Bouquet' },
  { icon: '🌹', label: 'Rose' },
  { icon: '🌺', label: 'Hibiscus' },
  { icon: '🌸', label: 'Cherry Blossom' },
  { icon: '🌼', label: 'Daisy' },
  { icon: '🌿', label: 'Herb' },
  { icon: '🍀', label: 'Lucky' },
  { icon: '🌵', label: 'Cactus' },
  { icon: '🍄', label: 'Mushroom' },
  { icon: '🦋', label: 'Butterfly' },
  { icon: '🐝', label: 'Bee' },
  { icon: '🐞', label: 'Ladybug' },
  { icon: '🦅', label: 'Eagle' },
  { icon: '🐬', label: 'Dolphin' },
  { icon: '🐳', label: 'Whale' },
  { icon: '🦈', label: 'Shark' },
  { icon: '🐙', label: 'Octopus' },
  { icon: '🐠', label: 'Tropical Fish' },
  { icon: '🦀', label: 'Crab' },
  { icon: '🐧', label: 'Penguin' },
  { icon: '🦁', label: 'Lion' },
  { icon: '🐘', label: 'Elephant' },
  { icon: '🦒', label: 'Giraffe' },
  { icon: '🐒', label: 'Monkey' },
  { icon: '🦊', label: 'Fox' },
  { icon: '🐻', label: 'Bear' },
  { icon: '🐼', label: 'Panda' },
  { icon: '🐨', label: 'Koala' },
  { icon: '🦘', label: 'Kangaroo' },
  { icon: '🦜', label: 'Parrot' },
  { icon: '🦉', label: 'Owl' },
  { icon: '🐍', label: 'Snake' },
  { icon: '🐢', label: 'Turtle' },
  { icon: '🦎', label: 'Lizard' },
  { icon: '🐊', label: 'Crocodile' },
  { icon: '🎷', label: 'Saxophone' },
  { icon: '♠️', label: 'Spades' },
  { icon: '♥️', label: 'Hearts' },
  { icon: '♦️', label: 'Diamonds' },
  { icon: '♣️', label: 'Clubs' },
  { icon: '🃏', label: 'Joker' },
];
